### PR TITLE
Reformat C++ code.

### PR DESCRIPTION
**Pull request by Rombur**
One thing that we still need to decide is the number of blank lines between functions implementation. You don't use any rule, sometimes it's even zero :-( This was not changed by clang format so we can just do it by hand when we work in a file. I usually use two lines but deal uses three lines. Just let me know what you prefer.

### CODE REVIEW

**Comment by dalg24** [comment]
2 lines is fine

**Comment by dalg24** [comment]
check failed but I think it is some kind of timeout when pushing to dockerhub

**Comment by dalg24** [comment]
I would prefer 4 spaces indentation

**Comment by Rombur** [comment]
New version of the formatting. Let me know if there is something that you don't like.

**Comment by Rombur** [comment]
New formatting is done. Merge the branch if you like it.

**Comment by Rombur** [comment]
I have squashed the commit.

**Comment by dalg24** [comment]
amen

**Pull request merged**
